# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="simstring",
    version="1.0.0",
    description="A Python implementation of the SimString, a simple and efficient algorithm for approximate string matching.",
    python_requires="==3.*,>=3.7.0",
    author="Julien Tourille",
    author_email="julien.tourille@gmail.com",
    license="MIT",
    packages=[
        "simstring",
        "simstring.database",
        "simstring.feature_extractor",
        "simstring.measure",
    ],
    package_dir={"": "."},
    package_data={},
    install_requires=["pymongo==3.*,>=3.11.3"],
    extras_require={
        "dev": [
            "black==20.*,>=20.8.0.b1",
            "dephell==0.*,>=0.8.3",
            "flake8==3.*,>=3.8.4",
            "jupyterlab==3.*,>=3.0.7",
            "pre-commit==2.*,>=2.9.3",
        ]
    },
)
